sudo: required
services:
  - docker

before_install:
  - docker build -t sk224400/docker-react-project -f Dockerfile.dev .
script:
  - docker run sk224400/docker-react-project npm run test -- --coverage